apiVersion: v1
kind: Service
metadata: 
  name: post-service
spec:
  ports:
    - port: 80
      targetPort: 5000
      name: http
  selector:
    name: post-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: post-service
spec:
  template:
    metadata:
      labels:
        name: post-service
    spec:
      containers:
        - name: post-service
          image: posts:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata: 
  name: tag-service
spec:
  ports:
    - port: 80
      targetPort: 5001
      name: http
  selector:
    name: tag-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tag-service
spec:
  template:
    metadata:
      labels:
        name: tag-service
    spec:
      containers:
        - name: tag-service
          image: tags:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata: 
  name: category-service
spec:
  ports:
    - port: 80
      name: http
  selector:
    name: category-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: category-service
spec:
  template:
    metadata:
      labels:
        name: category-service
    spec:
      containers:
        - name: category-service
          image: categories:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata: 
  name: gateway-service
spec:
  type: NodePort
  ports:
    - port: 80
      name: http
  selector:
    name: gateway-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway-service
spec:
  template:
    metadata:
      labels:
        name: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
